# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "struct_packing"
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["TOKITA Hiroshi"]
  s.date = "2013-02-16"
  s.description = "* Read/Write ruby object to byte array with C-like struct declarations."
  s.email = ["tokita.hiroshi@gmail.com"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "C-like_structure_declaration.rdoc",
    "Gemfile",
    "History.txt",
    "LICENSE.txt",
    "Manifest.txt",
    "PostInstall.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/struct_packing.rb",
    "lib/struct_packing/base.rb",
    "lib/struct_packing/packable.rb",
    "lib/struct_packing/unpackable.rb",
    "lib/struct_packing/util.rb",
    "script/console",
    "script/console.cmd",
    "script/destroy",
    "script/destroy.cmd",
    "script/generate",
    "script/generate.cmd",
    "struct_packing.gemspec",
    "test/struct_packing/test_base.rb",
    "test/struct_packing/test_packable.rb",
    "test/struct_packing/test_unpackable.rb",
    "test/struct_packing/test_util.rb",
    "test/test_helper.rb",
    "test/test_struct_packing.rb"
  ]
  s.homepage = "http://github.com/TOKITAHiroshi/struct_packing"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.25"
  s.summary = "* Read/Write ruby object to byte array with C-like struct declarations."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.2.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.2.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.2.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
  end
end

